config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  get 'jobs/premium', as: 'premium_jobs'
  get 'ola/mundo'
  root to: "jobs#premium"
  get 'premium' => 'jobs#premium'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
  validates_presence_of :description, :title
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[show edit update destroy]
  # GET /jobs or /jobs.json
  def index
    @jobs = Job.all
    respond_to do |format|
      format.html
      format.json { render json: @jobs}
    end
  end

  # GET /jobs/1 or /jobs/1.json
  def show; end

  def premium
    @jobs = Job.where(premium: true).all
  end
  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit; end

  # POST /jobs or /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, flash: { notice: 'Job was successfully created.'} }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { 
          flash[:notice] = 'Job was successfully updated.'
          redirect_to @job
        }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, flash: { alert: 'Job was successfully destroyed.'} }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_job
    @job = Job.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def job_params
    params.require(:job).permit(:title, :description, :premium)
  end
end

app/controllers/ola_controller.rb
class OlaController < ApplicationController
  def mundo
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/ola_helper.rb
module OlaHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: job) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title , class:"form-control" %>
  </div>

  <div class="field">
    <%= form.label :premium %><br>
    <%= form.check_box  :premium , class:"form-check-input"%>
  </div>  

  <div class="field">
    <%= form.label :description %> 
    <%= form.text_area :description , class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-primary" %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<h3>
    <%= job.title %>
    <% if job.premium %>
        <strong>(Premium)</strong>
    <% else %>
    <% end %>
</h3>
    <%= simple_format job.description%>

<p>
    <td><%= link_to 'Show', job , class:'btn btn-outline-info btn-sm' %></td> 
    <td><%= link_to 'Edit', edit_job_path(job), class:'btn btn-outline-secondary btn-sm' %></td> 
    <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-outline-danger btn-sm' %></td>
</p>

app/views/jobs/_nav-bar.html.erb
<nav class="navbar navbar-expand-sm navbar-dark bg-dark">
  <div class="container-fluid", role="navigation">

    <%= link_to 'Job Board', jobs_path, class:"navbar-brand"%>
    
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Premium', root_path, class:"nav-link active"%>
        </li>
       <li class="nav-item">
          <%= link_to 'Create a Job!', new_job_path, class:"nav-link active"%>
        </li>
        <li class="nav-item">
          <%= link_to 'Time', ola_mundo_path, class:"nav-link active"%>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>


<%= link_to 'Back', jobs_path, class:'btn btn-outline-info btn-sm' %>

app/views/jobs/index.html.erb
<!-- Mensagem quando exclui-->
<% if flash[:alert]%>
	<div class = "alert alert-danger" role = "alert"> <%= flash[:alert]%> </div>
    
<% end %>
<!-- Mensagem quando atualiza e cria-->
<% if flash[:notice1]%>
	<div class= "alert alert-success" role = "alert"> <%= flash[:notice1]%> </div>
<% end %>


<h1>Jobs</h1>

<%= render @jobs %>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/premium.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs Premium</h1>

<%= render @jobs %>

app/views/jobs/show.html.erb
<!-- Mensagem quando atualiza e cria-->
<% if flash[:notice]%>
	<div class= "alert alert-success" role = "alert"> <%= flash[:notice]%> </div>
<% end %>

<br>

<h3>
  <strong>Title:</strong><br></h3>
<p>
  <%= @job.title %>
</p>

<h3>
  <strong>Description:</strong><br></h3>
<p>
  <%= @job.description %>
</p>

<%= link_to 'Edit', edit_job_path(@job),class:'btn btn-outline-secondary btn-sm' %> 
<%= link_to 'Back', jobs_path, class:'btn btn-outline-info btn-sm' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Teste</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'jobs/nav-bar' %>
    <br>
    <div class="container">
    <%= yield %>
    </div>
  </body>
</html>

app/views/ola/mundo.html.erb
<h1>Ola#mundo</h1>
<h3>
<%= Time.now %>
</h3>